enhavo_setting_admin_setting_index:
    path: /setting/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_setting_admin_api_setting_index
                api_parameters:
                    group: expr:query.get("group")
        _endpoint:
            type: admin

enhavo_setting_admin_setting_create:
    path: /setting/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_setting_admin_api_setting_create
        _endpoint:
            type: admin

enhavo_setting_admin_setting_update:
    path: /setting/update/{id}
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_setting_admin_api_setting_update
        _endpoint:
            type: admin

